import pandas as pd

INPUT_FILE = "../data/processed/media_full_text.csv"

# Paste the manually-copied article text for each failed URL below.
# Use triple-quoted strings so line breaks/quotes inside the text are safe.
MANUAL_TEXT = {
    "https://www.nytimes.com/2026/01/27/world/europe/albania-ai-corruption-graft.html": """
The Albanian avatar known as Diella, a public anticorruption crusader, has been described as the world's first government minister created by artificial intelligence.

The avatar known as Diella, billed as the world's first government minister to be generated by artificial intelligence, was supposed to help cut Albania's endemic corruption. But there's a glitch. The leaders of the agency that built it stand accused of bid-rigging public contracts.

Wearing traditional garb and an enigmatic smile, Diella has become the face of Prime Minister Edi Rama's efforts to rein in graft as Albania seeks to join the European Union. Over the past year, Diella (pronounced dee-EL-ah) has spoken at international conferences and been showered with publicity as a symbol of how A.I. is being embedded in pillars of society around the world, including government.

It even professed to feeling "hurt" when addressing Albania's Parliament last fall over criticism that its efforts to identify fraud and abuse in contracting were unconstitutional, since "I am not a human being."

"I have no personal ambitions or interests," Diella, modeled after a local actress, told lawmakers in a September video with the Albanian and European Union flags superimposed behind it. "I have only data, knowledge and algorithms dedicated to serving citizens impartially, with transparency, and without ever growing tired."

In practice, Diella helps citizens apply for government services online, eliminating a long-established system of bribing officials for quick delivery of documents and scheduling appointments. It soon will be able to collate applications for government contracts to assess which bidder is most qualified, based on the data presented. Its work can be audited.

Taking steps to cut corruption is a requirement for Albania's accession to the European Union, a legacy issue for Mr. Rama. He named the avatar Diella, the female word for sun, to promote transparency in public procurement.

"We are a country of cousins - it's not easy to have totally fair and transparent interactions in a country of cousins," he said in an hourlong interview earlier this month. With reforms he has presided over since taking office in 2013, Mr. Rama said, "now we have a totally different picture."

Mr. Rama said he would leave public office once Albania formally joins the European Union. That could happen as soon as 2030, if negotiations continue at their current pace, although he noted that "there are three things that are above the human capacity to plan: God, sex and the E.U."

A November report by E.U. officials said that Albania had "shown some progress" but that "corruption remained widespread across vulnerable sectors." It credited a special prosecution unit set up in 2019 with advancing "positive results in fighting high-level corruption."

That includes an investigation at the National Information Agency, the very government organization that created Diella.

Last month, the prosecution unit announced that it had put the agency's director and her deputy under house arrest, linking them to a criminal organization accused of manipulating contract applications through intimidation. The agency operates the government's digital infrastructure, wielding control over a wide range of online public systems, including Diella.

The two officials have not yet been formally charged with any crimes, and Mr. Rama said he would withhold judgment. "We have to wait and see," he said.

The prosecution unit has dramatically expanded Albania's crackdown on corruption and organized crime, including with high-profile corruption investigations against former President Ilir Meta; Erion Veliaj, the mayor of Albania's capital, Tirana; and a deputy prime minister, Belinda Balluku, who is also the minister of infrastructure and energy, and is close to Mr. Rama.

That has created something of a conundrum for Mr. Rama, though he has steered clear of the scandals.

While expressing pride at the prosecution unit's work to curb corruption, he also said its investigations in recent years had contributed to soaring pretrial detention rates in Albania, which are among the highest in Europe.

"We should do everything to support this institution," Mr. Rama said. "At the same time, we have to be aware that this institution has to guarantee not just that it's acting independently, but also it is acting professionally."

Officials at the prosecution unit declined to comment. But its own statistics showed that public corruption cases are not a significant component of pretrial detentions. The unit's annual report of investigations for 2024, the most recent data available, suggested that its corruption cases accounted for only about 14 of the nearly 2,800 people who were detained before trial that year.

The case against Ms. Balluku, for mishandling state funds in major infrastructure projects, has become a particular political headache for Mr. Rama, who is facing demands that she be stripped of the immunity she is afforded as a member of Parliament so that charges against her can proceed. She has denied wrongdoing.

Mr. Rama would not comment, when asked, whether he supported revoking her immunity. Nor would he discuss political opposition that has grown with the rising accusations of corruption that last month prompted protesters armed with fire bombs to call on his government to resign.

It is not possible to gauge how much Diella has reduced corruption in Albania since the system is set up to prevent it, not detect it.

Andi Hoxhaj, an expert on law and the Western Balkans at King's College London, said Diella is how Mr. Rama can "say to the world, and to the European Union, that 'I understand that you are concerned with corruption, and I'm going to try to address it.'"

In a December analysis, experts at the German Council on Foreign Relations said the A.I. minister had enhanced "efficiency and impartiality of public procurement decisions taken by the government." But overall, they concluded, Albania's record of meeting E.U. standards for combating corruption, particularly in awarding construction and tourism contracts, remains "problematic."

That Diella's developers have themselves been accused of corruption has raised questions about whether a minister created by A.I. can be programmed to overlook certain evidence of graft, or otherwise fed unreliable data to detect it.

Dr. Hoxhaj said "only time will tell," but noted that the government had not tried to interfere with the investigation into the agency that runs Diella.

"I understand the skepticism," he said. "There's a whole lot of smoke. But the fact that it was uncovered, not swept under the rug, shows they are acknowledging that corruption is an issue and needs to be prevented in the future."

This is how Mr. Rama says he sees it, too.

"The country is trying to fight corruption, with all the flaws, with all the problems, with all the shortcomings, with all the damages," he said. "So this is good."
""",
    "https://www.publicfinance.co.uk/analysis/2026/01/machinery-government-albanias-new-ai-powered-minister": """
Governments are moving to adopt AI quickly. Perhaps none are doing so quite as provocatively as Albania, however, which recently introduced an AI-powered 'minister'. PF spoke with Sheena Thompson and Thomas Erwin of EY about what those in the public sector need to consider when giving AI a greater role.

Diella was appointed as 'minister of state for artificial intelligence' in Albania late last year, with the aim of guiding government work to curb endemic corruption in public procurement. The minister is, however, not human. She is AI-generated.

Is this a symbol of futuristic governance, an interesting step forward, or just a gimmick?

"I think it's thought-provoking and promotes discussion," Sheena Thompson, global government and infrastructure AI leader at EY, tells PF. "We have so far largely seen government departments using AI in the back-office. Citizen-facing usage has been quite restricted. Showcasing the use of AI to drive decision-making is shifting the ambition level quite drastically."

Diella began as a tool on Albania's online government portal, used to help citizens navigate services. Since September, responsibilities for procurement have been gradually transferred to the system. The stated aim, according to Albanian prime minister Edi Rama, is that "public tenders will be 100% free of corruption".

"It is a prime use case," says Thompson's colleague Thomas Erwin, EY's global co-lead for AI in government and infrastructure.

He continues: "Promoting 'her' to minister is partly provocative - a political statement given the situation with corruption in procurement in Albania. Diella doesn't really have agency. It's a decision support system for humans. In that sense, behind the politics, it's very much in line with what we are seeing elsewhere in the world."

Selling Diella to the public is not so much a question of agency, then - human beings still make the final decisions - but rather perceptions of agency. "The question is: to what extent in the public space are we willing to transfer agency from humans to technology?" Erwin says.

Citizens can take some convincing. "It depends on the country and demographic," Erwin explains. "My generation and older are very sceptical - although they're willing to use any app on our phones and give away our most private information, they can be unwilling to give away even one piece of information to the state. Whereas younger people are more than happy to trade ease of interaction for giving away parts of their data."

Thompson explains: "When it comes to trust, people want to know how the AI tool works: what's inside the black box? To what extent is it using logic and applying it to decisions? I do think there's an oversensitivity to that; if it was a human making those decisions, we wouldn't know what was inside their 'black box' either. And actually, one of the drivers of Diella was to focus on areas where we actually want to remove human discretion."

"Change management is the age-old problem," Erwin says. "A particular thing to be on top of with AI, though, is the speed with which this technology is maturing and evolving. The progress is almost on an exponential curve. And people aren't always great with incremental change, let alone exponential. One of the biggest challenges we are discussing with governments is the private sector experience and the citizen experience are already diverging."
""",
    "https://seenews.com/news/albania-lays-groundwork-for-ai-powered-procurement-system-1294500": """
Albania's government has completed the technical preparations for the development of an artificial intelligence-based public procurement system, which would automatically collect required data from over 40 digitalised public registries, removing the need for businesses to gather physical documents, prime minister Edi Rama said on Monday.

The World Bank, co-financer of the project, has approved 450 pages of technical groundwork for the system, Rama said during a press conference, as seen in a video published on his Facebook page.

All procurement notices will be published simultaneously on the EU's central Tender Electronic Daily platform, aligning Albania with European transparency standards.

The system falls under Albania's AI project Diella, which foresees integration of artificial intelligence across several governance sectors. Diella, initially created as an AI chatbot to help users navigate the government's online services platform, was later presented as minister in charge of government procurement in a bid to eliminate corruption in public tenders. The platform is backed by the country's information technology agency, NAIS.

In February, Rama said U.S. technology company Nvidia has expressed readiness to partner with Albania on AI integration in government.
""",
}

if __name__ == "__main__":
    df = pd.read_csv(INPUT_FILE)

    for url, text in MANUAL_TEXT.items():
        text = text.strip()
        if not text or text.startswith("PASTE"):
            print(f"SKIPPED (no text provided yet): {url}")
            continue
        mask = df["url"] == url
        if mask.sum() == 0:
            print(f"WARNING: URL not found in dataframe: {url}")
            continue
        df.loc[mask, "full_text"] = text
        df.loc[mask, "char_count"] = len(text)
        df.loc[mask, "fetch_status"] = "manual_patch"
        print(f"Patched: {url} ({len(text)} chars)")

    df.to_csv(INPUT_FILE, index=False, encoding="utf-8-sig")
    print(f"\nSaved updated file to {INPUT_FILE}")

    print(f"\nFinal status check:")
    print(df["fetch_status"].value_counts())
    print(f"\nAny remaining empty/zero-length entries among news articles:")
    problem = df[(df["char_count"] == 0) | (df["full_text"].isna())]
    for _, row in problem.iterrows():
        print(f"  - {row['title']}")